package com.xunqin.common.constant;

public interface VolunteerActivityConstant {

    // 活动类型
    String ACTIVITY_TYPE_INFO_VERIFY = "INFO_VERIFY";
    String ACTIVITY_TYPE_CLUE_INVESTIGATE = "CLUE_INVESTIGATE";
    String ACTIVITY_TYPE_VOLUNTEER_RECRUIT = "VOLUNTEER_RECRUIT";
    String ACTIVITY_TYPE_COMMUNITY_PROMOTION = "COMMUNITY_PROMOTION";

    String[] ALL_ACTIVITY_TYPES = {
            ACTIVITY_TYPE_INFO_VERIFY,
            ACTIVITY_TYPE_CLUE_INVESTIGATE,
            ACTIVITY_TYPE_VOLUNTEER_RECRUIT,
            ACTIVITY_TYPE_COMMUNITY_PROMOTION
    };

    // 活动状态
    int ACTIVITY_STATUS_DRAFT = 0;
    int ACTIVITY_STATUS_RECRUITING = 1;
    int ACTIVITY_STATUS_IN_PROGRESS = 2;
    int ACTIVITY_STATUS_ENDED = 3;
    int ACTIVITY_STATUS_CANCELLED = 4;

    // 参与状态
    int PARTICIPANT_STATUS_PENDING = 0;
    int PARTICIPANT_STATUS_APPROVED = 1;
    int PARTICIPANT_STATUS_REJECTED = 2;
    int PARTICIPANT_STATUS_QUIT = 3;

    // 报告状态
    int REPORT_STATUS_PENDING = 0;
    int REPORT_STATUS_APPROVED = 1;
    int REPORT_STATUS_REJECTED = 2;

    // 进度类型
    String PROGRESS_TYPE_UPDATE = "UPDATE";
    String PROGRESS_TYPE_NOTICE = "NOTICE";
    String PROGRESS_TYPE_RESULT = "RESULT";
}
